### PR TITLE
Add examples demonstrating the usage of whatpack's synchronous messag…

### LINKED ISSUE #1: This project does not have enough video or examples
i need help in this young and enthusiastic contributors

### PR DESCRIPTION
**Pull request by Parvezkhan0**
Fixes #1

### CODE REVIEW

**Review by SigireddyBalasai — CHANGES_REQUESTED** [review]
whats.open_web is not needed bro

**Comment by SigireddyBalasai** [comment]
thank you for your enthusiasm

**Comment by SigireddyBalasai** [comment]
@Parvezkhan0

**Comment by Parvezkhan0** [comment]
@SigireddyBalasai sorry for delay, I will just fix it now

**Comment by Parvezkhan0** [comment]
@SigireddyBalasai I made the necessary changes, please review it

**Review by SigireddyBalasai — APPROVED** [review]
Thank you bro i  am looking  forward for  new contributions

**Pull request merged**
